#!/usr/bin/env bash

# clean_tract.sh :: Multi-subject wrapper to prune thalamocortical tracts
# generated by generate_tracts.sh.
#
# For each subject this script:
#   1) Loads merged hemisphere tractograms
#      (<SUBJECT>_{lh,rh}_thalamocortical.tck)
#   2) Enforces ROI endpoint consistency (motor cortex <-> thalamus)
#   3) Removes extreme streamline-length outliers
#   4) Removes low-density orphan streamlines using a TDI threshold mask

set -u

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <DWI_DATA_DIR> [<SUBJECT_ID>]"
    echo ""
    echo "Where:"
    echo "  <DWI_DATA_DIR>   - Base directory containing subject folders"
    echo "  <SUBJECT_ID>     - Optional: Process only this subject"
    exit 1
fi

DWI_DATA_DIR="$1"
SUBJECT_ID="${2:-}"

# Cleanup parameters (tunable defaults)
MIN_LEN_MM=20
MAX_LEN_MM=250
MIN_DENSITY=2

echo "DWI data directory: $DWI_DATA_DIR"
[ -n "$SUBJECT_ID" ] && echo "Processing only subject: $SUBJECT_ID" || echo "Processing all subjects"

for cmd in tckedit tckmap mrthreshold; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "Required MRtrix command not found in PATH: $cmd"
        exit 1
    fi
done

clean_hemi_tract() {
    local input_tck="$1"
    local roi_motor="$2"
    local roi_thal="$3"
    local template_img="$4"
    local output_tck="$5"
    local tmp_dir="$6"
    local hemi_label="$7"

    if [ ! -f "$input_tck" ]; then
        echo "  [$hemi_label] Input tract missing: $input_tck"
        return 1
    fi

    local tmp_filtered="$tmp_dir/${hemi_label}_filtered.tck"
    local tmp_tdi="$tmp_dir/${hemi_label}_tdi.mif"
    local tmp_mask="$tmp_dir/${hemi_label}_keepmask.mif"

    # Pass 1: keep streamlines that connect both ROIs, prune extreme lengths.
    tckedit "$input_tck" "$tmp_filtered" \
        -include "$roi_motor" \
        -include "$roi_thal" \
        -ends_only \
        -minlength "$MIN_LEN_MM" \
        -maxlength "$MAX_LEN_MM" \
        -quiet

    # Pass 2: build a tract density image and keep streamlines that pass through
    # voxels with at least MIN_DENSITY streamlines to reduce isolated orphans.
    tckmap "$tmp_filtered" "$tmp_tdi" -template "$template_img" -precise -quiet
    mrthreshold "$tmp_tdi" -abs "$MIN_DENSITY" "$tmp_mask" -quiet
    tckedit "$tmp_filtered" "$output_tck" -mask "$tmp_mask" -quiet

    rm -f "$tmp_filtered" "$tmp_tdi" "$tmp_mask"
    return 0
}

process_subject() {
    local subject_name="$1"

    local dwi_dir="$DWI_DATA_DIR/$subject_name/DWI"
    local tract_dir="$DWI_DATA_DIR/$subject_name/Tractography/thalamocortical"
    local roi_dir="$DWI_DATA_DIR/$subject_name/Rois"

    local template_img=""
    if [ -f "$dwi_dir/combined_dwi_denoised_degibbs_1stVol_brain_mask.nii.gz" ]; then
        template_img="$dwi_dir/combined_dwi_denoised_degibbs_1stVol_brain_mask.nii.gz"
    elif [ -f "$dwi_dir/AP_brain_mask.nii.gz" ]; then
        template_img="$dwi_dir/AP_brain_mask.nii.gz"
    else
        echo "Brain mask template not found for subject $subject_name. Skipping."
        return
    fi

    local roi_mc_lh="$roi_dir/aparc+aseg_lh_motorcortex_DTIsp.nii.gz"
    local roi_mc_rh="$roi_dir/aparc+aseg_rh_motorcortex_DTIsp.nii.gz"
    local roi_thal_l="$roi_dir/aparc+aseg_10_left_thalamus_DTIsp.nii.gz"
    local roi_thal_r="$roi_dir/aparc+aseg_49_right_thalamus_DTIsp.nii.gz"

    if [ ! -d "$tract_dir" ]; then
        echo "Tract directory missing for subject $subject_name: $tract_dir. Skipping."
        return
    fi

    if [ ! -f "$roi_mc_lh" ] || [ ! -f "$roi_mc_rh" ] || [ ! -f "$roi_thal_l" ] || [ ! -f "$roi_thal_r" ]; then
        echo "One or more DWI-space ROIs missing for subject $subject_name in $roi_dir. Skipping."
        return
    fi

    local in_lh="$tract_dir/${subject_name}_lh_thalamocortical.tck"
    local in_rh="$tract_dir/${subject_name}_rh_thalamocortical.tck"
    local out_lh="$tract_dir/${subject_name}_lh_thalamocortical_cleaned.tck"
    local out_rh="$tract_dir/${subject_name}_rh_thalamocortical_cleaned.tck"

    local tmp_dir="$tract_dir/.clean_tmp"
    mkdir -p "$tmp_dir"

    echo "Cleaning thalamocortical tracts for subject $subject_name"

    clean_hemi_tract "$in_lh" "$roi_mc_lh" "$roi_thal_l" "$template_img" "$out_lh" "$tmp_dir" "lh"
    local lh_status=$?
    clean_hemi_tract "$in_rh" "$roi_mc_rh" "$roi_thal_r" "$template_img" "$out_rh" "$tmp_dir" "rh"
    local rh_status=$?

    rm -rf "$tmp_dir"

    if [ $lh_status -eq 0 ] && [ $rh_status -eq 0 ]; then
        echo "Finished cleaning thalamocortical tracts for subject $subject_name"
    else
        echo "Completed with warnings for subject $subject_name"
    fi
}

if [ -n "$SUBJECT_ID" ]; then
    process_subject "$SUBJECT_ID"
else
    # Keep discovery behavior aligned with generate_tracts.sh.
    for subject_dir in "$DWI_DATA_DIR"/*/; do
        if [ ! -d "$subject_dir" ]; then
            continue
        fi
        subject_name=$(basename "$subject_dir")
        process_subject "$subject_name"
    done
fi

echo "Thalamocortical tract cleanup complete."