#!/usr/bin/env bash

# roi_registration.sh :: Register FreeSurfer ROIs to DWI space
# to DWI space for multiple subjects or a single subject.
#
# This script is designed to be compatible with:
#   - fs_segmentation.sh (for running FreeSurfer SynthSeg 2.0)
#   - roi_conversion.sh  (for creating aparc+aseg-based ROI masks from SynthSeg)
#   - DWI_processing.py  (for preprocessing DWI data)
#
# Registers the following ROIs to DWI space:
#   - Brainstem
#   - Thalamus (Left/Right)
#   - Motor cortex combined (Left/Right) - precentral + paracentral
#   - Individual precentral gyrus (Left/Right)
#
# Expected directory / filename layout per subject:
#   T1 (input structural image):
#       <NIFTI_BASE_DIR>/<SUBJECT>/T1/<SUBJECT>_T1.nii.gz
#
#   Optional SynthSeg output (for masked T1 registration target):
#       <SYNTHSEG_SUBJECTS_DIR>/<SUBJECT>/mri/aparc+aseg.nii.gz
#   ROIs (after roi_conversion.sh):
#       <NIFTI_BASE_DIR>/<SUBJECT>/T1/Rois/
#           aparc+aseg_16_brainstem.nii.gz
#           aparc+aseg_10_left_thalamus.nii.gz
#           aparc+aseg_49_right_thalamus.nii.gz
#           aparc+aseg_1024_lh_precentral.nii.gz
#           aparc+aseg_2024_rh_precentral.nii.gz
#           aparc+aseg_lh_motorcortex.nii.gz
#           aparc+aseg_rh_motorcortex.nii.gz
#
#   DWI (after DWI_processing.py):
#       <DWI_DATA_DIR>/<SUBJECT>/AP_1stVol.nii.gz (or similar b0)

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
	echo "Usage: $0 <DWI_DATA_DIR> <SYNTHSEG_SUBJECTS_DIR> [<SUBJECT_ID>]"
	echo ""
	echo "Where:"
	echo "  <DWI_DATA_DIR>         - Base directory containing subject folders with DWI data (from DWI_processing.py)"
	echo "  <SYNTHSEG_SUBJECTS_DIR> - SynthSeg output directory (subject/mri/aparc+aseg.nii.gz)"
	echo "  <SUBJECT_ID>           - Optional: Process only this subject (must begin with HC)"
	exit 1
fi

DWI_DATA_DIR="$1"            # e.g., /export01/data/Ethan-COMP-401
SYNTHSEG_SUBJECTS_DIR="$2"   # SynthSeg output directory (subject/mri/aparc+aseg.nii.gz)
SUBJECT_ID="$3"              # optional

echo "DWI data directory: $DWI_DATA_DIR"
echo "SynthSeg subjects directory: $SYNTHSEG_SUBJECTS_DIR"
[ -n "$SUBJECT_ID" ] && echo "Processing only subject: $SUBJECT_ID" || echo "Processing all subjects"

register_subject() {
	local subject_name="$1"

	local t1_file="$DWI_DATA_DIR/$subject_name/T1/${subject_name}_T1.nii.gz"
	local synthseg_aparc="$SYNTHSEG_SUBJECTS_DIR/$subject_name/mri/aparc+aseg.nii.gz"
	local dwi_dir="$DWI_DATA_DIR/$subject_name"
	
	# DWI_processing.py creates AP_1stVol.nii.gz as the b0 reference
	# Try multiple possible b0 file names generated by DWI_processing.py
	local b0_file=""
	if [ -f "$dwi_dir/AP_1stVol.nii.gz" ]; then
		b0_file="$dwi_dir/AP_1stVol.nii.gz"
	elif [ -f "$dwi_dir/AP_Cor.nii.gz" ]; then
		b0_file="$dwi_dir/AP_Cor.nii.gz"
	else
		echo "No b0 DWI file found for subject $subject_name. Expected AP_1stVol.nii.gz or AP_Cor.nii.gz in $dwi_dir. Skipping."
		return
	fi

	# ROIs are stored in T1/Rois/ directory per roi_conversion.sh
	local roi_dir="$DWI_DATA_DIR/$subject_name/T1/Rois"
	
	# Define all ROIs to register
	local roi_bs="$roi_dir/aparc+aseg_16_brainstem.nii.gz"
	local roi_thal_l="$roi_dir/aparc+aseg_10_left_thalamus.nii.gz"
	local roi_thal_r="$roi_dir/aparc+aseg_49_right_thalamus.nii.gz"
	local roi_mc_lh="$roi_dir/aparc+aseg_lh_motorcortex.nii.gz"
	local roi_mc_rh="$roi_dir/aparc+aseg_rh_motorcortex.nii.gz"
	local roi_precentral_lh="$roi_dir/aparc+aseg_1024_lh_precentral.nii.gz"
	local roi_precentral_rh="$roi_dir/aparc+aseg_2024_rh_precentral.nii.gz"

	# Basic existence checks
	if [ ! -f "$t1_file" ]; then
		echo "T1 file not found for subject $subject_name at $t1_file. Skipping."
		return
	fi

	if [ ! -d "$roi_dir" ]; then
		echo "ROI directory not found for subject $subject_name at $roi_dir. Skipping."
		return
	fi

	# Check that at least the brainstem ROI exists
	if [ ! -f "$roi_bs" ]; then
		echo "Brainstem ROI not found for subject $subject_name in $roi_dir. Skipping."
		return
	fi

	echo "Registering ROIs to DWI space for subject $subject_name"

	local file_t1w="$t1_file"
	local file_b0="$b0_file"

	# Output registered ROIs to T1/Rois/ directory per organizational setup
	local output_dir="$roi_dir"

	# Determine the names of output files based on T1
	local t1w_name
	t1w_name="$(basename "${file_t1w%.nii*}")"

	# Make a tmp folder that will be deleted at the end of the script
	local tmp_dir
	mkdir -p "$output_dir/${t1w_name}_T1w_2_DWI_tmp"
	tmp_dir="$output_dir/${t1w_name}_T1w_2_DWI_tmp"

	# If SynthSeg aparc is available, use it to build a brain-masked T1 for more robust registration.
	if [ -f "$synthseg_aparc" ]; then
		fslmaths "$synthseg_aparc" -bin "$tmp_dir/synthseg_brainmask_tmp.nii.gz"
		fslmaths "$t1_file" -mul "$tmp_dir/synthseg_brainmask_tmp.nii.gz" "$tmp_dir/${t1w_name}_brain_tmp.nii.gz"
		file_t1w="$tmp_dir/${t1w_name}_brain_tmp.nii.gz"
	fi

	# 1. Register DWI_b0 to T1w using FLIRT; we obtain the matrix DWI_b0_reg_2_T1w
	flirt -dof 6 -cost mutualinfo \
		-in "$file_b0" -ref "$file_t1w" \
		-omat "$tmp_dir/DWI_b0_reg_2_T1w_tmp.mat"

	# 2. Convert DWI_b0_reg_2_T1w matrix to MRtrix format
	transformconvert -quiet \
		"$tmp_dir/DWI_b0_reg_2_T1w_tmp.mat" "$file_b0" "$file_t1w" flirt_import \
		"$tmp_dir/DWI_b0_reg_2_T1w_tmp.txt"

	# 3. Apply the inverse of the DWI_b0_reg_2_T1w matrix to obtain T1w_DTIsp
	mrtransform -quiet "$file_t1w" \
		-inverse -linear "$tmp_dir/DWI_b0_reg_2_T1w_tmp.txt" \
		"$output_dir/${t1w_name}_DTIsp.nii.gz"

	# 4. Register all ROIs to DWI space using the inverse transformation
	# Function to register a single ROI
	register_roi() {
		local roi_file="$1"
		local roi_name="$2"
		
		if [ ! -f "$roi_file" ]; then
			echo "  ! ROI not found: $roi_name (skipping)"
			return
		fi
		
		local roi_basename
		roi_basename="$(basename "${roi_file%.nii*}")"
		local output_roi="$output_dir/${roi_basename}_DTIsp.nii.gz"
		
		echo "  - Registering $roi_name to DWI space"
		mrtransform -quiet "$roi_file" \
			-inverse -linear "$tmp_dir/DWI_b0_reg_2_T1w_tmp.txt" \
			"$output_roi"
	}

	# Register all ROIs
	register_roi "$roi_bs" "Brainstem"
	register_roi "$roi_thal_l" "Left Thalamus"
	register_roi "$roi_thal_r" "Right Thalamus"
	register_roi "$roi_mc_lh" "Motor Cortex (LH)"
	register_roi "$roi_mc_rh" "Motor Cortex (RH)"
	register_roi "$roi_precentral_lh" "Precentral Gyrus (LH)"
	register_roi "$roi_precentral_rh" "Precentral Gyrus (RH)"

	# Remove tmp folder
	rm -r "$tmp_dir"

	echo "Finished ROI registration for subject $subject_name"
}

if [ -n "$SUBJECT_ID" ]; then
	register_subject "$SUBJECT_ID"
else
	# Auto-discover all HC* subjects in the DWI data directory
	for subject_dir in "$DWI_DATA_DIR"/HC*/; do
		if [ ! -d "$subject_dir" ]; then
			continue
		fi
		subject_name=$(basename "$subject_dir")
		register_subject "$subject_name"
	done
fi

echo "ROI registration complete."