"""
average_tract.py :: computes the average along-tract value of each diffusion metric (FA, MD, AD, RD) per subject,
using the tract profiles generated by compute_tract_profile.py.

Usage: python average_tract.py <profile_dir> <output_csv> [<subject_id>]
    profile_dir : directory containing the .pkl files produced by compute_tract_profile.py
    output_csv  : path to write the resulting CSV summary
    subject_id  : optional – a specific subject, or 'HC'/'MS' to filter subjects in the profiles
"""

import pickle
import sys
import os
from os.path import join as pjoin
import pandas as pd

METRICS = ['fa', 'md', 'ad', 'rd']


def average_tract(profile_dir, output_csv, subject_id=None):
    """Load per-metric tract profiles and compute the mean value across nodes for each subject."""
    records = []

    for metric_name in METRICS:
        pkl_path = pjoin(profile_dir, f'{metric_name}.pkl')
        if not os.path.exists(pkl_path):
            print(f"Warning: {pkl_path} not found, skipping {metric_name}.")
            continue

        with open(pkl_path, 'rb') as f:
            lh_df, rh_df = pickle.load(f)

        # Filter subjects if a subject_id or group prefix (HC/MS) was provided
        if subject_id is not None:
            if subject_id in ('HC', 'MS'):
                cols = [c for c in lh_df.columns if c.startswith(subject_id)]
            else:
                cols = [c for c in lh_df.columns if c == subject_id]
            lh_df = lh_df[cols]
            rh_df = rh_df[[c for c in cols if c in rh_df.columns]]

        # Mean across all nodes (rows) for each subject (column)
        lh_means = lh_df.mean(axis=0)
        rh_means = rh_df.mean(axis=0)

        for subject in lh_means.index:
            records.append({
                'subject': subject,
                'metric': metric_name,
                'lh_mean': lh_means[subject],
                'rh_mean': rh_means.get(subject, float('nan')),
            })

    results = pd.DataFrame(records)
    results.to_csv(output_csv, index=False)
    print(f"Saved average tract values to {output_csv}")


if __name__ == "__main__":
    profile_dir = sys.argv[1]
    output_csv = sys.argv[2]
    subject_id = sys.argv[3] if len(sys.argv) > 3 else None
    average_tract(profile_dir, output_csv, subject_id)
