"""
compute_tract_profile.py :: computes the along-tract profile of diffusion metrics (FA, MD, AD, RD) for each subject, and outputs the profiles as pickle files.
The along-tract profile is essentially the value of the diffusion metric at each node along the tract. The implementation of this function is based off of work by Yeatman et al. in 2012.

Usage: python compute_tract_profile.py <base_dir> <output_dir> [<subject_id>]
    subject_id : optional – a specific subject, or 'HC'/'MS' to process only that group
"""

import pickle
import sys
import os
from os.path import join as pjoin
import numpy as np
import pandas as pd
from utils import load_nifti, load_tck_file, get_tract_profile

# The 4 DTI metrics generated by DWI_processing.py
METRICS = ['fa', 'md', 'ad', 'rd']

def _resolve_dwi_dir(base, subject):
    """Resolve the DWI directory for a subject, matching DWI_processing.py layout."""
    dwi_subdir = pjoin(base, subject, 'DWI')
    if os.path.isdir(dwi_subdir):
        return dwi_subdir
    return pjoin(base, subject)


def _resolve_brain_mask(dwi_dir):
    """Find the brain mask with fallbacks matching generate_tracts.sh. Returns None if not found."""
    candidates = [
        pjoin(dwi_dir, 'combined_dwi_denoised_degibbs_1stVol_brain_mask.nii.gz'),
        pjoin(dwi_dir, 'AP_brain_mask.nii.gz'),
    ]
    for path in candidates:
        if os.path.isfile(path):
            return path
    return None


def compute_tract_profile(base, out, subject_id=None):
    '''
    This function computes the along-tract profile of diffusion metrics (FA, MD, AD, RD) for each subject, and outputs the profiles as pickle files.
    The along-tract profile is essentially the value of the diffusion metric at each node along the tract. The implementation of this function is based off of work by Yeatman et al. in 2012.

    Expected per-subject layout (from DWI_processing.py + generate_tracts.sh):
        <base>/<subject>/DWI/
            <subject>_dti_{fa,md,ad,rd}_dipy.nii.gz
            combined_dwi_denoised_degibbs_1stVol_brain_mask.nii.gz (or AP_brain_mask.nii.gz)
        <base>/<subject>/Tractography/thalamocortical/
            <subject>_lh_thalamocortical.tck
            <subject>_rh_thalamocortical.tck
    '''
    # List of subjects to process
    subjects = sorted([
        d for d in os.listdir(base)
        if os.path.isdir(pjoin(base, d))
    ])

    # Filter subjects if a subject_id or group prefix (HC/MS) was provided
    if subject_id is not None:
        if subject_id in ('HC', 'MS'):
            subjects = [s for s in subjects if s.startswith(subject_id)]
        else:
            subjects = [s for s in subjects if s == subject_id]

    # Initialize a pair of DataFrames (lh, rh) per metric
    metric_dfs = {m: (pd.DataFrame(), pd.DataFrame()) for m in METRICS}

    for subject in subjects:
        print(f"Processing {subject}...")

        dwi_dir = _resolve_dwi_dir(base, subject)
        ref_path = _resolve_brain_mask(dwi_dir)

        if ref_path is None:
            print(f"  Brain mask not found for {subject}, skipping.")
            continue

        tract_dir = pjoin(base, subject, 'Tractography', 'thalamocortical')
        lh_path = pjoin(tract_dir, f'{subject}_lh_thalamocortical.tck')
        rh_path = pjoin(tract_dir, f'{subject}_rh_thalamocortical.tck')

        if not os.path.isfile(lh_path) or not os.path.isfile(rh_path):
            print(f"  Tract files missing for {subject}, skipping.")
            continue

        lh = load_tck_file(lh_path, ref_path)
        rh = load_tck_file(rh_path, ref_path)

        for metric_name in METRICS:
            metric_path = pjoin(dwi_dir,
                                f'{subject}_dti_{metric_name}_dipy.nii.gz')
            if not os.path.isfile(metric_path):
                print(f"  Metric {metric_name} not found for {subject}, skipping.")
                continue
            metric_img, metric_aff = load_nifti(metric_path)

            # Get the along tract profile of the metric
            lh_profile = get_tract_profile(lh, metric_img, metric_aff,
                                            use_weights=True)
            rh_profile = get_tract_profile(rh, metric_img, metric_aff,
                                            use_weights=True)

            metric_dfs[metric_name][0][subject] = lh_profile
            metric_dfs[metric_name][1][subject] = rh_profile

    # Fill in NaN values and save each metric as a pickle file
    for metric_name in METRICS:
        lh_df, rh_df = metric_dfs[metric_name]
        lh_df.fillna(method='ffill', inplace=True)
        rh_df.fillna(method='ffill', inplace=True)

        output_path = pjoin(out, f'{metric_name}.pkl')
        with open(output_path, 'wb') as handle:
            pickle.dump([lh_df, rh_df], handle, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"Saved {metric_name} profiles to {output_path}")

if __name__ == "__main__":

    # Base directory containing all subject data
    base = sys.argv[1]
    out = sys.argv[2]
    subject_id = sys.argv[3] if len(sys.argv) > 3 else None
    
    compute_tract_profile(base, out, subject_id)