"""
compute_tract_profile.py :: computes the along-tract profile of diffusion metrics (FA, MD, AD, RD) for each subject, and outputs the profiles as pickle files.
The along-tract profile is essentially the value of the diffusion metric at each node along the tract. The implementation of this function is based off of work by Yeatman et al. in 2012.

Usage: python compute_tract_profile.py <base_dir> <output_dir>
"""

import pickle
import sys
import os
from os.path import join as pjoin
import numpy as np
import pandas as pd
from utils import load_nifti, load_tck, get_tract_profile

# The 4 DTI metrics generated by DWI_processing.py
METRICS = ['fa', 'md', 'ad', 'rd']

def compute_tract_profile(base, out):
    '''
    This function computes the along-tract profile of diffusion metrics (FA, MD, AD, RD) for each subject, and outputs the profiles as pickle files.
    The along-tract profile is essentially the value of the diffusion metric at each node along the tract. The implementation of this function is based off of work by Yeatman et al. in 2012.
    '''
    # List of subjects to process
    subjects = sorted(os.listdir(base))

    # Initialize a pair of DataFrames (lh, rh) per metric
    metric_dfs = {m: (pd.DataFrame(), pd.DataFrame()) for m in METRICS}

    for subject in subjects:
        print(f"Processing {subject}...")

        b0_path = pjoin(base, subject, 'dwi', subject[:-3]+'_dwi_b0_noskull.nii.gz')

        lh_path = pjoin(base, subject, 'cst', subject[:-3]+'_lh_cst_edit.tck')
        rh_path = pjoin(base, subject, 'cst', subject[:-3]+'_rh_cst_edit.tck')

        lh = load_tck(lh_path)
        rh = load_tck(rh_path)

        for metric_name in METRICS:
            metric_path = pjoin(base, subject, 'metrics',
                                subject[:-3]+'_dti_'+metric_name+'_dipy.nii.gz')
            metric_img, metric_aff = load_nifti(metric_path)

            # Get the along tract profile of the metric
            lh_profile = get_tract_profile(lh, metric_img, metric_aff,
                                            use_weights=True)
            rh_profile = get_tract_profile(rh, metric_img, metric_aff,
                                            use_weights=True)

            metric_dfs[metric_name][0][subject] = lh_profile
            metric_dfs[metric_name][1][subject] = rh_profile

    # Fill in NaN values and save each metric as a pickle file
    for metric_name in METRICS:
        lh_df, rh_df = metric_dfs[metric_name]
        lh_df.fillna(method='ffill', inplace=True)
        rh_df.fillna(method='ffill', inplace=True)

        output_path = pjoin(out, f'{metric_name}.pkl')
        with open(output_path, 'wb') as handle:
            pickle.dump([lh_df, rh_df], handle, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"Saved {metric_name} profiles to {output_path}")

if __name__ == "__main__":

    # Base directory containing all subject data
    base = sys.argv[1]
    out = sys.argv[2]
    
    compute_tract_profile(base, out)